update SQL Server README
hasura/ndc-sqlserver pull request #138
Opened 2024-06-27 16:15 UTC by pranshi06

### What

### How

2024-06-27 16:27 UTC, rsd1122 requested changes

2024-06-27 16:27 UTC, rsd1122 commented on README.md
> +schema in `hml` format. In a new terminal tab from the root of your project, run:
```suggestion
schema in `hml` format. In a new terminal tab from your project's root directory run:
```

2024-06-27 16:27 UTC, rsd1122 commented on README.md
> +You can do this in one convenience command. From the root of your project, run:
```suggestion
You can do this with just one command. From your project's root directory, run:
```

2024-06-27 16:27 UTC, rsd1122 commented on README.md
> +directory is used by the docker-compose file to serve the engine locally. From the root of your project, run:
```suggestion
directory is used by the docker-compose file to serve the engine locally. From your project's root directory, run:
```

2024-06-27 16:34 UTC, pranshi06 commented
@rsd1122 I've addressed the review comments. Please have a look.

2024-06-27 16:44 UTC, rsd1122 approved these changes

2024-06-27 16:45 UTC, rsd1122 commented
Changes approved. Feel free to merge.

2024-06-27 16:45 UTC, rsd1122 approved these changes

2024-06-28 08:10 UTC, codingkarthik approved these changes

2024-06-28 08:14 UTC, merged